export interface ChecklistItem {
  id: string
  criterion: string
  level: 'A' | 'AA' | 'AAA'
  title: string
  description: string
  howToCheck: string
}

export interface ChecklistCategory {
  id: string
  title: string
  description: string
  items: ChecklistItem[]
}

export const wcagChecklistData: ChecklistCategory[] = [
  {
    id: 'images',
    title: 'Imagens e Multimédia',
    description: 'Texto alternativo e descrições para conteúdo visual',
    items: [
      {
        id: 'img-1',
        criterion: '1.1.1',
        level: 'A',
        title: 'Texto alternativo em imagens',
        description: 'Todas as imagens informativas têm texto alternativo descritivo',
        howToCheck: 'Verificar se todas as tags <img> têm atributo alt com descrição adequada',
      },
      {
        id: 'img-2',
        criterion: '1.1.1',
        level: 'A',
        title: 'Imagens decorativas marcadas corretamente',
        description: 'Imagens decorativas têm alt vazio ou role="presentation"',
        howToCheck: 'Verificar se imagens puramente decorativas têm alt="" ou role="presentation"',
      },
      {
        id: 'img-3',
        criterion: '1.4.5',
        level: 'AA',
        title: 'Texto não está em imagens',
        description: 'Texto importante não é apresentado como imagem (exceto logotipos)',
        howToCheck: 'Verificar se texto importante está em HTML real e não em imagens',
      },
      {
        id: 'img-4',
        criterion: '1.4.9',
        level: 'AAA',
        title: 'Ícones têm alternativas',
        description: 'Ícones que transmitem informação têm texto alternativo ou label',
        howToCheck: 'Verificar se ícones informativos têm aria-label ou texto visível',
      },
    ],
  },
  {
    id: 'color-contrast',
    title: 'Contraste e Cor',
    description: 'Legibilidade e uso adequado de cores',
    items: [
      {
        id: 'color-1',
        criterion: '1.4.3',
        level: 'AA',
        title: 'Contraste de texto normal (4.5:1)',
        description: 'Texto normal tem rácio de contraste mínimo de 4.5:1',
        howToCheck: 'Usar ferramenta como WebAIM Contrast Checker para verificar',
      },
      {
        id: 'color-2',
        criterion: '1.4.3',
        level: 'AA',
        title: 'Contraste de texto grande (3:1)',
        description: 'Texto grande (18pt+ ou 14pt bold) tem contraste mínimo de 3:1',
        howToCheck: 'Verificar contraste de títulos e texto destacado',
      },
      {
        id: 'color-3',
        criterion: '1.4.11',
        level: 'AA',
        title: 'Contraste de elementos UI (3:1)',
        description: 'Botões, inputs e ícones têm contraste adequado',
        howToCheck: 'Verificar contraste de bordas, ícones e estados de focus',
      },
      {
        id: 'color-4',
        criterion: '1.4.1',
        level: 'A',
        title: 'Cor não é o único indicador',
        description: 'Informação não depende apenas da cor para ser compreendida',
        howToCheck: 'Verificar se erros, estados e links usam mais que apenas cor',
      },
    ],
  },
  {
    id: 'keyboard',
    title: 'Navegação por Teclado',
    description: 'Acesso completo sem uso de rato',
    items: [
      {
        id: 'kbd-1',
        criterion: '2.1.1',
        level: 'A',
        title: 'Tudo acessível por teclado',
        description: 'Todas as funcionalidades podem ser usadas apenas com teclado',
        howToCheck: 'Testar navegação com Tab, Enter, Space e setas',
      },
      {
        id: 'kbd-2',
        criterion: '2.1.2',
        level: 'A',
        title: 'Sem armadilhas de teclado',
        description: 'O utilizador não fica "preso" em nenhum elemento',
        howToCheck: 'Verificar se consegue sair de todos os elementos com Tab ou Escape',
      },
      {
        id: 'kbd-3',
        criterion: '2.4.7',
        level: 'AA',
        title: 'Focus visível',
        description: 'O indicador de focus é claramente visível',
        howToCheck: 'Navegar com Tab e verificar se o focus é sempre visível',
      },
      {
        id: 'kbd-4',
        criterion: '2.4.3',
        level: 'A',
        title: 'Ordem de focus lógica',
        description: 'A ordem de navegação por Tab segue uma sequência lógica',
        howToCheck: 'Verificar se a ordem de Tab segue o fluxo visual da página',
      },
      {
        id: 'kbd-5',
        criterion: '2.4.1',
        level: 'A',
        title: 'Skip links disponíveis',
        description: 'Existe opção para saltar para o conteúdo principal',
        howToCheck: 'Pressionar Tab no início da página e verificar se aparece "Saltar para conteúdo"',
      },
    ],
  },
  {
    id: 'forms',
    title: 'Formulários',
    description: 'Labels, erros e instruções claras',
    items: [
      {
        id: 'form-1',
        criterion: '1.3.1',
        level: 'A',
        title: 'Labels associados aos inputs',
        description: 'Todos os campos têm labels programaticamente associados',
        howToCheck: 'Verificar se cada input tem <label for="id"> ou aria-label',
      },
      {
        id: 'form-2',
        criterion: '3.3.2',
        level: 'A',
        title: 'Instruções e dicas visíveis',
        description: 'Campos com formato específico têm instruções claras',
        howToCheck: 'Verificar se campos como data, telefone têm texto de ajuda',
      },
      {
        id: 'form-3',
        criterion: '3.3.1',
        level: 'A',
        title: 'Erros identificados claramente',
        description: 'Erros de validação indicam o campo e o problema',
        howToCheck: 'Submeter formulário com erros e verificar mensagens',
      },
      {
        id: 'form-4',
        criterion: '3.3.3',
        level: 'AA',
        title: 'Sugestões de correção',
        description: 'Mensagens de erro sugerem como corrigir o problema',
        howToCheck: 'Verificar se erros explicam como resolver o problema',
      },
      {
        id: 'form-5',
        criterion: '4.1.2',
        level: 'A',
        title: 'Campos obrigatórios marcados',
        description: 'Campos obrigatórios têm indicação visual e aria-required',
        howToCheck: 'Verificar se campos required têm * ou texto "obrigatório"',
      },
    ],
  },
  {
    id: 'structure',
    title: 'Estrutura e Semântica',
    description: 'HTML semântico e landmarks ARIA',
    items: [
      {
        id: 'struct-1',
        criterion: '1.3.1',
        level: 'A',
        title: 'Hierarquia de headings correta',
        description: 'Headings seguem ordem lógica (h1 > h2 > h3)',
        howToCheck: 'Usar extensão HeadingsMap ou inspecionar código',
      },
      {
        id: 'struct-2',
        criterion: '1.3.1',
        level: 'A',
        title: 'Landmarks/regiões definidas',
        description: 'Página usa header, main, nav, footer ou roles ARIA',
        howToCheck: 'Verificar existência de elementos semânticos ou roles',
      },
      {
        id: 'struct-3',
        criterion: '1.3.1',
        level: 'A',
        title: 'Listas marcadas corretamente',
        description: 'Listas usam <ul>, <ol> ou <dl> apropriadamente',
        howToCheck: 'Verificar se listas visuais usam elementos de lista HTML',
      },
      {
        id: 'struct-4',
        criterion: '1.3.1',
        level: 'A',
        title: 'Tabelas com headers',
        description: 'Tabelas de dados têm <th> e scope definido',
        howToCheck: 'Verificar se tabelas têm cabeçalhos marcados com <th>',
      },
      {
        id: 'struct-5',
        criterion: '2.4.2',
        level: 'A',
        title: 'Título de página descritivo',
        description: 'Cada página tem <title> único e descritivo',
        howToCheck: 'Verificar o título no separador do browser',
      },
    ],
  },
  {
    id: 'links',
    title: 'Links e Navegação',
    description: 'Links descritivos e navegação consistente',
    items: [
      {
        id: 'link-1',
        criterion: '2.4.4',
        level: 'A',
        title: 'Links descritivos',
        description: 'Texto dos links indica o destino (evitar "clique aqui")',
        howToCheck: 'Verificar se links fazem sentido fora do contexto',
      },
      {
        id: 'link-2',
        criterion: '2.4.4',
        level: 'A',
        title: 'Links em nova janela avisados',
        description: 'Links que abrem em nova janela indicam isso ao utilizador',
        howToCheck: 'Verificar se target="_blank" tem indicação visual/texto',
      },
      {
        id: 'link-3',
        criterion: '3.2.3',
        level: 'AA',
        title: 'Navegação consistente',
        description: 'Menu de navegação é consistente em todas as páginas',
        howToCheck: 'Navegar entre páginas e verificar consistência do menu',
      },
      {
        id: 'link-4',
        criterion: '3.2.4',
        level: 'AA',
        title: 'Identificação consistente',
        description: 'Elementos com a mesma função têm o mesmo estilo',
        howToCheck: 'Verificar se botões e links similares são apresentados igual',
      },
    ],
  },
  {
    id: 'video-audio',
    title: 'Vídeo e Áudio',
    description: 'Legendas, transcrições e controlos',
    items: [
      {
        id: 'media-1',
        criterion: '1.2.2',
        level: 'A',
        title: 'Vídeos têm legendas',
        description: 'Vídeos com áudio têm legendas sincronizadas',
        howToCheck: 'Verificar se vídeos têm opção de legendas',
      },
      {
        id: 'media-2',
        criterion: '1.2.1',
        level: 'A',
        title: 'Áudio tem transcrição',
        description: 'Conteúdo apenas áudio tem transcrição em texto',
        howToCheck: 'Verificar se podcasts/áudios têm versão texto',
      },
      {
        id: 'media-3',
        criterion: '1.4.2',
        level: 'A',
        title: 'Áudio automático controlável',
        description: 'Áudio que inicia automaticamente pode ser pausado',
        howToCheck: 'Verificar se há controlo para parar áudio automático',
      },
      {
        id: 'media-4',
        criterion: '2.2.2',
        level: 'A',
        title: 'Animações podem ser pausadas',
        description: 'Conteúdo em movimento pode ser pausado ou ocultado',
        howToCheck: 'Verificar se carrosséis e animações têm controlos',
      },
    ],
  },
  {
    id: 'responsive',
    title: 'Responsividade',
    description: 'Adaptação a diferentes dispositivos e preferências',
    items: [
      {
        id: 'resp-1',
        criterion: '1.4.4',
        level: 'AA',
        title: 'Zoom até 200% funcional',
        description: 'Conteúdo é legível com zoom de 200% no browser',
        howToCheck: 'Fazer zoom a 200% e verificar se conteúdo não se sobrepõe',
      },
      {
        id: 'resp-2',
        criterion: '1.4.10',
        level: 'AA',
        title: 'Reflow em ecrãs pequenos',
        description: 'Não há scroll horizontal em 320px de largura',
        howToCheck: 'Testar em viewport de 320px e verificar scroll',
      },
      {
        id: 'resp-3',
        criterion: '1.4.12',
        level: 'AA',
        title: 'Espaçamento de texto ajustável',
        description: 'Conteúdo adapta-se a espaçamento de texto aumentado',
        howToCheck: 'Aumentar line-height e letter-spacing e verificar layout',
      },
      {
        id: 'resp-4',
        criterion: '2.5.5',
        level: 'AAA',
        title: 'Áreas de toque adequadas',
        description: 'Botões e links têm tamanho mínimo de 44x44px',
        howToCheck: 'Verificar tamanho de elementos interativos em mobile',
      },
    ],
  },
]
